on:
    workflow_dispatch:
    push:
      branches: [ main ]
jobs:
    my-job:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: my-step
              run: | 
                ls
                pwd
