on:
    workflow_dispatch:
    push:
      branches: [ main ]
jobs:
    my-job:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: create venv and install dependencies
              run: |
                if (-Not (Test-Path "venv")) {python -m venv venv;Write-Output "Virtual environment created."} else {Write-Output "Virtual environment already exists."}
                ./venv/Scripts/activate
                pip install -r .\requirements.txt
            - name: test enviroment
              run: |
                ./venv/Scripts/activate
                python --version
                pip --version
                pip freeze
            - name: make exe
              run: |
                ./venv/Scripts/activate
                pyinstaller .\Main.spec --noconfirm
            - name: make setup
              run: iscc .\innosetup.iss