on:
    workflow_dispatch:
    push:
      branches: [ main ]
jobs:
    my-job:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: make exe
              run: pyinstaller .\Main.spec --noconfirm
            - name: make setup
              run: iscc .\innosetup.iss