on:
    workflow_dispatch:
    push:
      branches: [ main ]
jobs:
    my-job:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: create venv
              run: if (-Not (Test-Path "venv")) {python -m venv venv;Write-Output "Virtual environment created."} else {Write-Output "Virtual environment already exists."}
            - name: activate venv
              run: ./venv/Scripts/activate
            - name: test enviroment
              run: |
                python --version
                pip --version
                pip freeze
            - name: install dependencies
              run: pip install -r .\requirements.txt
            - name: make exe
              run: pyinstaller .\Main.spec --noconfirm
            - name: make setup
              run: iscc .\innosetup.iss