on:
    workflow_dispatch:
    push:
      branches: [ main ]
jobs:
    my-job:
        runs-on: self-hosted
        steps:
            - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
            - uses: actions/checkout@v4
            - uses: getsentry/action-setup-venv@v2.1.0
              id: venv
              with:
                python-version: 3.11.8
                cache-dependency-path: |
                  requirements.txt
                install-cmd: pip install -r requirements.txt
                venv-dir: venv
            - name: test venv
              run: |
                python --version
                pip --version
                pip freeze
            - name: make exe
              run: pyinstaller .\Main.spec --noconfirm
            - name: make setup
              run: iscc .\innosetup.iss