on:
    workflow_dispatch:
    push:
      branches: [ main ]
jobs:
    my-job:
        runs-on: self-hosted
        steps:
            - name: my-step
              run: | 
                pyinstaller .\Main.spec --noconfirm
                iscc .\innosetup.iss
